# Generated by Django 5.2.17 on 2026-09-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_education_user_phone_user_resume_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], default='day', max_length=20),
        ),
    ]
