# Generated by Django 5.2.17 on 2026-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_job_mode_job_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='Fresher', max_length=50),
        ),
    ]
